export enum NotificationMessageCodeEnum {
  LOGGED_IN = 'LOGGED_IN',
  LOGGED_OUT = 'LOGGED_OUT',
  CREATED = 'CREATED',
  CATEGORY_CREATED = 'CATEGORY_CREATED',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  CATEGORY_DELETED = 'CATEGORY_DELETED',
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  TRANSACTION_DELETED = 'TRANSACTION_DELETED',
}
